version: '3.4'

services:
  facesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:80
    ports:
      - "5300:80"
      #- "443"
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  faces.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - OrdersApiUrl=http://ordersapi
      - SignalRHubUrl=http://localhost:5200
    ports:
      - "5100:80"
      #- "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  notificationservice:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrdersContextConnection=server=sqldbService;Database=OrdersApiDb;User Id=sa;Password=BigPassw0rd
      - FacesApiUrl=http://facesapi/api/faces
    ports:
      - "5200:80"

